shared_buffers = 8GB
max_connections = 1024
max_wal_size = 4GB

autovacuum_work_mem = 4GB
effective_cache_size = 16GB
maintenance_work_mem = 1GB
max_parallel_workers = 16
max_parallel_workers_per_gather = 16
max_worker_processes = 16
work_mem = 64MB
shared_preload_libraries = 'pg_stat_statements,pgaudit'
default_toast_compression = 'lz4'